export const PAYPAL_FUNDING_SOURCES = [
    { APPLEPAY: "applepay" },
    {
        BANCONTACT: "bancontact",
    },
    {
        BLIK: "blik",
    },
    {
        BOLETO: "boleto",
    },
    {
        BOLETOBANCARIO: "boletobancario",
    },
    {
        CARD: "card",
    },
    {
        CREDIT: "credit",
    },
    {
        EPS: "eps",
    },
    {
        GIROPAY: "giropay",
    },
    {
        IDEAL: "ideal",
    },
    {
        ITAU: "itau",
    },
    {
        MAXIMA: "maxima",
    },
    {
        MERCADOPAGO: "mercadopago",
    },
    {
        MULTIBANCO: "multibanco",
    },
    {
        MYBANK: "mybank",
    },
    {
        OXXO: "oxxo",
    },
    {
        P24: "p24",
    },
    {
        PAIDY: "paidy",
    },
    {
        PAYLATER: "paylater",
    },
    {
        PAYPAL: "paypal",
    },
    {
        PAYU: "payu",
    },
    {
        SATISPAY: "satispay",
    },
    {
        SEPA: "sepa",
    },
    {
        SOFORT: "sofort",
    },
    {
        TRUSTLY: "trustly",
    },
    {
        VENMO: "venmo",
    },
    {
        WECHATPAY: "wechatpay",
    },
    { ZIMPLER: "zimpler" },
];